version: '3.8'

services:
  comfyui:
    build: .
    container_name: comfyui
    environment:
      - HSA_OVERRIDE_GFX_VERSION=11.0.0
      - VK_ICD_FILENAMES=/usr/share/vulkan/icd.d/amd_icd64.json
      - ROC_ENABLE_PRE_VEGA=1
    devices:
      - /dev/dri:/dev/dri
      - /dev/kfd:/dev/kfd
    ports:
      - "8188:8188"
    networks:
      - unicorn-network
    volumes:
      - ./models:/app/models
      - ./input:/app/input
      - ./output:/app/output
      - ./custom_nodes:/app/custom_nodes
    restart: unless-stopped

networks:
  unicorn-network:
    external: true
