#cloud-config
autoinstall:
  version: 1
  
  # Explicitly disable all interactive prompts - critical for 25.04
  interactive-sections: []

  # Basic locale settings
  locale: en_US.UTF-8
  
  # Explicit keyboard configuration with all fields
  keyboard:
    layout: us
    variant: ""
    toggle: null

  # Network configuration - simple single interface to prevent loops
  network:
    version: 2
    ethernets:
      # Configure first ethernet interface found - prevents loop issues
      primary:
        match:
          name: "eno1"
        dhcp4: true
        dhcp6: false
        dhcp4-overrides:
          use-routes: true

  # Storage - simplified but robust configuration with 16GB swap for AI
  storage:
    layout:
      name: lvm
    swap:
      size: 16G

  # Create ucadmin user with correct password
  identity:
    hostname: UC-1
    username: ucadmin
    # Password is "MagicUnicorn!8-)"
    password: "$6$iWv5c3HHG.FBORkG$mOLNq./L7/CFTeFHouXy87/70GGOHUcnWHtch8OSgHUFgzmW/CbPRk0Tj52uwx2SxIyst7q/D2RvJtG7j2Ygy1"
    realname: "UnicornCommander Admin"

  # Enable SSH
  ssh:
    install-server: true
    allow-pw: true

  # Package selection - only packages available in Ubuntu 25.04 default repos
  packages:
    # System essentials
    - openssh-server
    - curl
    - wget
    - git
    - nano
    - vim
    - htop
    - unzip
    - build-essential
    - software-properties-common
    - apt-transport-https
    - ca-certificates
    - gnupg
    - lsb-release

    # Network management (will switch to this in late-commands)
    - network-manager

    # Development tools
    - python3
    - python3-pip
    - python3-venv
    - python3-dev

    # Basic GPU support (ROCm will be added in late-commands)
    - linux-firmware
    - mesa-vulkan-drivers
    - vulkan-tools

  # Apply security updates during installation
  updates: security

  # Minimal late-commands to avoid parsing issues
  late-commands:
    - echo 'ucadmin ALL=(ALL) NOPASSWD:ALL' > /target/etc/sudoers.d/ucadmin-nopasswd
    - chmod 440 /target/etc/sudoers.d/ucadmin-nopasswd
    - curtin in-target --target=/target -- systemctl disable systemd-networkd
    - curtin in-target --target=/target -- systemctl enable NetworkManager

  # Power off instead of reboot to allow USB removal
  shutdown: poweroff
