version: '3.8'

networks:
  unicorn-network:
    external: true

services:
  unicorn-embedding-server:
    build: .
    container_name: unicorn-embedding-server
    hostname: embedding-server
    ports:
      - "8000:8000"   # Main API endpoint
      - "9991:9991"   # Embedding server direct access
      - "9992:9992"   # Reranker server direct access
    volumes:
      - "./models:/app/models"
      - "./logs:/app/logs"
    environment:
      - LLAMA_VULKAN=1
      - LLAMA_VULKAN_FORCE=1
      - VK_ICD_FILENAMES=/usr/share/vulkan/icd.d/radeon_icd.x86_64.json
      - VULKAN_DEVICE=0
    devices:
      - /dev/dri:/dev/dri  # AMD GPU access (Vulkan-only)
    networks:
      - unicorn-network
    privileged: true  # Required for AMD GPU access
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    extra_hosts:
      - "host.docker.internal:host-gateway"
