site_name: UC-1 Documentation
site_description: Complete documentation for UC-1 Unicorn Commander system
site_author: Magic Unicorn Unconventional Technology & Stuff Inc.
site_url: http://localhost:7911

repo_name: Unicorn-Commander/UC-1
repo_url: https://github.com/Unicorn-Commander/UC-1

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.top
    - search.highlight
    - search.share
    - content.code.copy
    - content.code.annotate
  palette:
    - scheme: default
      primary: purple
      accent: pink
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: purple
      accent: pink
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  icon:
    logo: material/unicorn
    repo: fontawesome/brands/github

plugins:
  - search

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - admonition
  - pymdownx.details
  - pymdownx.tasklist:
      custom_checkbox: true
  - toc:
      permalink: true
  - attr_list
  - md_in_html

nav:
  - Home: index.md
  - About:
    - Overview: about/overview.md
    - Magic Unicorn: about/magic-unicorn.md
    - Hardware Specs: about/hardware.md
  - Installation:
    - Quick Start: installation/quick-start.md
  - Components:
    - Software Stack: components/stack.md
    - The Colonel: components/the-colonel.md
  - API Reference:
    - Embedding API: api/embedding.md
  - Guides:
    - Getting Started: guides/getting-started.md
  - Support:
    - FAQ: support/faq.md

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/Unicorn-Commander
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/AaronStransky
  version:
    provider: mike